modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="theultramod"
version="1.0.0"
displayName="The ultra mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Yoshi azul 12347, MCreator"

[[dependencies.theultramod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



